---

- name: "create backend directory"
  file:
    path: ~/backend
    state: directory

- name: "unarchive backend"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend
- name: "installing node dependencies"
  shell: | 
    cd /home/ubuntu/backend
    echo "befor npm install -->"
    ls
    npm install
    echo "after npm install -->"
    ls
- name: "start the server"
  become: true
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start main.js
    # pm2 start npm -- start
  register: execute_node

- name: monitor
  debug:
    msg: "{{ execute_node.stdout_lines }}"


