---

- name: "create backend directory"
  become: true
  shell: | 
    mkdir ~/backend
    ls
    pwd

- name: "unarchive backend"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "update apt packages"
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "install nodejs and npm"
  become: true
  apt: 
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes


- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes

- name: "start the server"
  become: true
  shell: |
    cd ~/backend
    npm install
    cd dist
    pm2 stop default
    pm2 start npm -- start
  register: execute_node

- name: monitor
  debug:
    msg: "{{ execute_node.stdout_lines }}"


